name: Vulnerability Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * 1'  # Run weekly on Mondays

permissions:
  contents: read
  pull-requests: write

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run govulncheck-pr action
        uses: your-org/csgda-platform-actions/workflows/govulncheck-pr@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
