name: 'Use govulncheck composite action'

on:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays
  workflow_dispatch:  # Allow manual trigger

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run govulncheck and create PR
        uses: ./.github/actions/govulncheck-pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: main
